---

- hosts: localhost
  connection: local
  gather_facts: false
  
  tasks:
  
  - name: Hello
    ping:

- name: "Test roles"
  hosts: localhost
  connection: local
  gather_facts: false

  pre_tasks:

  - command: "ansible --version"
    register: ansible_output

  - debug: var=ansible_output

  - pause:
      minutes: 3

  roles:
  - role: geerlingguy.java
  
# - name: "Test collection"
#   hosts: localhost
#   connection: local
#   gather_facts: false
# 
#   collections:
#     - geerlingguy.php_roles
# 
#   roles:
#     - php
#     - role: php-versions
#       vars:
#         php_version: '7.3'
# 
