---

- hosts: localhost
  connection: local
  gather_facts: false
  
  tasks:
  
  - name: Hello
    ping:

- name: "Test roles"
  hosts: localhost
  connection: local
  gather_facts: false
  
  roles:
  - role: geerlingguy.java
  
- name: "Test collection"
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - import_role:
      name: rrey.my_collection.idiot

   
