---

- hosts: localhost
  connection: local
  gather_facts: false
  
  tasks:
  
  - name: Hello
    ping:
    
  - debug:
      var: item
    loop:
    - "{{ list_manual }}"
    - "{{ empty_string }}"
    - "{{ list_manual_area }}"
  - debug:
      var: hostvars['inventory_hostname']
    

- name: "Test roles"
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

  - command: "ansible --version"
    register: ansible_output

  - debug: var=ansible_output

  - shell: "ls -l ; cat ./ansible.cfg ; env|sort"
    register: env_output

  - debug: var=env_output


