- name: "Install Collection with galaxy"
  hosts: localhost
  gather_facts: false

  tasks:

  - name: "Collection directory"
    file:
      path: /tmp/ansible/ansible_collections/cisco/io
      state: directory

  - name: "Download collection"
    unarchive:
      src: https://github.com/ansible-collections/cisco.ios/archive/1.0.3.zip
      dest: /tmp/
      remote_src: true

  - name: "Rename"
    command: "mv /tmp/cisco.ios-1.0.3 /tmp/ansible/ansible_collections/cisco/ios/"

